'use client';

import React, { useState, useRef, useCallback } from 'react';
import { LandingHeader as Header } from '@/components/ui/landing-header';
import { LandingFooter as Footer } from '@/components/ui/landing-footer';
import { Upload, Paintbrush, Sparkles, FileCode, ChevronRight, Check, ArrowLeft } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import { toast } from 'sonner';

// ── Skin loader utility ────────────────────────────────────────────────────────

const SKIN_STORAGE_KEY = 'tripplet_custom_skin';

function applySkin(css: string) {
    let el = document.getElementById('tripplet-custom-skin');
    if (!el) {
        el = document.createElement('style');
        el.id = 'tripplet-custom-skin';
        document.head.appendChild(el);
    }
    el.textContent = css;
}

function removeSkin() {
    const el = document.getElementById('tripplet-custom-skin');
    if (el) el.remove();
    localStorage.removeItem(SKIN_STORAGE_KEY);
}

function saveSkin(css: string, name: string) {
    localStorage.setItem(SKIN_STORAGE_KEY, JSON.stringify({ css, name }));
    applySkin(css);
}

function loadSavedSkin(): { css: string; name: string } | null {
    try {
        const stored = localStorage.getItem(SKIN_STORAGE_KEY);
        return stored ? JSON.parse(stored) : null;
    } catch {
        return null;
    }
}

// ── Quickstart questions ───────────────────────────────────────────────────────

interface QuickstartQuestion {
    id: string;
    question: string;
    options: { label: string; value: string }[];
}

const QUESTIONS: QuickstartQuestion[] = [
    {
        id: 'vibe',
        question: 'What vibe are you going for?',
        options: [
            { label: 'Minimal & clean', value: 'minimal' },
            { label: 'Cozy & warm', value: 'cozy' },
            { label: 'Neon & cyberpunk', value: 'neon' },
            { label: 'Nature & earthy', value: 'nature' },
        ],
    },
    {
        id: 'background',
        question: 'What background color do you prefer?',
        options: [
            { label: 'Pure black (#000)', value: '#000000' },
            { label: 'Near black (#0A0A0A)', value: '#0A0A0A' },
            { label: 'Dark gray (#1A1A2E)', value: '#1A1A2E' },
            { label: 'Deep blue (#0D1117)', value: '#0D1117' },
        ],
    },
    {
        id: 'accent',
        question: 'Pick an accent color.',
        options: [
            { label: 'Cyan', value: '#00E5FF' },
            { label: 'Purple', value: '#B388FF' },
            { label: 'Green', value: '#69F0AE' },
            { label: 'Pink', value: '#FF80AB' },
        ],
    },
    {
        id: 'borders',
        question: 'How visible should borders be?',
        options: [
            { label: 'Subtle (barely visible)', value: 'subtle' },
            { label: 'Normal', value: 'normal' },
            { label: 'Prominent', value: 'prominent' },
        ],
    },
    {
        id: 'corners',
        question: 'What about rounded corners?',
        options: [
            { label: 'Sharp (0px)', value: '0' },
            { label: 'Slightly rounded (6px)', value: '0.375rem' },
            { label: 'Rounded (12px)', value: '0.75rem' },
            { label: 'Very rounded (16px)', value: '1rem' },
        ],
    },
];

function generateCSS(answers: Record<string, string>): string {
    const bg = answers.background || '#0A0A0A';
    const accent = answers.accent || '#00E5FF';
    const borderOpacity = answers.borders === 'subtle' ? '08' : answers.borders === 'prominent' ? '30' : '18';
    const radius = answers.corners || '0.75rem';

    // Derive colors from background
    const bgR = parseInt(bg.slice(1, 3), 16);
    const bgG = parseInt(bg.slice(3, 5), 16);
    const bgB = parseInt(bg.slice(5, 7), 16);
    const cardBg = `rgb(${Math.min(bgR + 10, 255)}, ${Math.min(bgG + 10, 255)}, ${Math.min(bgB + 10, 255)})`;
    const mutedBg = `rgb(${Math.min(bgR + 20, 255)}, ${Math.min(bgG + 20, 255)}, ${Math.min(bgB + 20, 255)})`;

    return `/* Tripplet Custom Skin — Generated by Quickstart */
/* Vibe: ${answers.vibe || 'custom'} */

:root {
    --background: ${bg} !important;
    --card: ${cardBg} !important;
    --muted: ${mutedBg} !important;
    --border: ${accent}${borderOpacity} !important;
    --ring: ${accent} !important;
    --radius: ${radius} !important;
}

/* Accent overrides */
.bg-brand, [class*="bg-brand"] {
    background-color: ${accent} !important;
}

.text-brand, [class*="text-brand"] {
    color: ${accent} !important;
}

/* Sidebar tint */
[data-sidebar] {
    background-color: ${bg} !important;
    border-color: ${accent}${borderOpacity} !important;
}

/* Input ring */
textarea:focus, input:focus {
    --tw-ring-color: ${accent}40 !important;
}

/* Scrollbar (WebKit) */
::-webkit-scrollbar-thumb {
    background: ${accent}30 !important;
}
::-webkit-scrollbar-thumb:hover {
    background: ${accent}50 !important;
}
`;
}

// ── Page ────────────────────────────────────────────────────────────────────────

export default function SkinsPage() {
    const [step, setStep] = useState(0);
    const [answers, setAnswers] = useState<Record<string, string>>({});
    const [generatedCSS, setGeneratedCSS] = useState<string | null>(null);
    const [activeSkin, setActiveSkin] = useState<{ css: string; name: string } | null>(null);
    const fileInputRef = useRef<HTMLInputElement>(null);

    // Load saved skin on mount
    React.useEffect(() => {
        const saved = loadSavedSkin();
        if (saved) {
            setActiveSkin(saved);
            applySkin(saved.css);
        }
    }, []);

    const handleAnswer = (questionId: string, value: string) => {
        setAnswers((prev) => ({ ...prev, [questionId]: value }));
        if (step < QUESTIONS.length - 1) {
            setTimeout(() => setStep((s) => s + 1), 300);
        }
    };

    const handleGenerate = () => {
        const css = generateCSS(answers);
        setGeneratedCSS(css);
        const name = `${answers.vibe || 'custom'}-skin`;
        saveSkin(css, name);
        setActiveSkin({ css, name });
        toast.success('Skin applied!', { description: 'Your custom skin is now active.' });
    };

    const handleReset = () => {
        setStep(0);
        setAnswers({});
        setGeneratedCSS(null);
    };

    const handleUpload = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;
        if (!file.name.endsWith('.css')) {
            toast.error('Invalid file', { description: 'Please upload a .css file.' });
            return;
        }
        const reader = new FileReader();
        reader.onload = (ev) => {
            const css = ev.target?.result as string;
            const name = file.name.replace(/\.css$/, '');
            saveSkin(css, name);
            setActiveSkin({ css, name });
            toast.success('Skin loaded!', { description: `Applied ${file.name}` });
        };
        reader.readAsText(file);
        e.target.value = '';
    }, []);

    const handleRemoveSkin = () => {
        removeSkin();
        setActiveSkin(null);
        toast('Skin removed', { description: 'Reverted to default theme.' });
    };

    const handleDownload = () => {
        if (!generatedCSS) return;
        const blob = new Blob([generatedCSS], { type: 'text/css' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${answers.vibe || 'custom'}-skin.css`;
        a.click();
        URL.revokeObjectURL(url);
        toast('Downloaded!', { description: 'Save it and share with friends.' });
    };

    const isLastQuestion = step === QUESTIONS.length - 1;
    const allAnswered = QUESTIONS.every((q) => answers[q.id]);

    return (
        <div className="min-h-screen bg-background text-foreground flex flex-col">
            <Header />

            <main className="flex-1 max-w-4xl mx-auto w-full px-6 py-16">
                {/* Back link */}
                <Link
                    href="/"
                    className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8"
                >
                    <ArrowLeft size={14} />
                    Back
                </Link>

                {/* Hero */}
                <div className="mb-12">
                    <div className="flex items-center gap-3 mb-4">
                        <h1 className="text-3xl font-extrabold tracking-tight">Skins</h1>
                        <span className="px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider bg-amber-500/15 text-amber-400 border border-amber-500/25 rounded-full">
                            Beta
                        </span>
                    </div>
                    <p className="text-muted-foreground text-base max-w-2xl leading-relaxed">
                        Customize Tripplet&apos;s look with CSS skins. Like Vencord or BetterDiscord themes — upload a <code className="font-mono text-foreground/80 bg-muted/50 px-1.5 py-0.5 rounded text-sm">.css</code> file and it overrides the default styles. No build step, no config files, just CSS.
                    </p>
                </div>

                {/* Active skin indicator */}
                {activeSkin && (
                    <motion.div
                        initial={{ opacity: 0, y: -8 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="mb-8 p-4 rounded-xl border border-emerald-500/20 bg-emerald-500/5"
                    >
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="h-8 w-8 rounded-lg bg-emerald-500/15 flex items-center justify-center">
                                    <Paintbrush size={14} className="text-emerald-400" />
                                </div>
                                <div>
                                    <p className="text-sm font-medium text-foreground">Active skin: <span className="text-emerald-400">{activeSkin.name}</span></p>
                                    <p className="text-xs text-muted-foreground">Custom CSS is applied on top of your theme.</p>
                                </div>
                            </div>
                            <button
                                onClick={handleRemoveSkin}
                                className="px-3 py-1.5 text-xs font-medium rounded-lg border border-border text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-all"
                            >
                                Remove
                            </button>
                        </div>
                    </motion.div>
                )}

                {/* How it works */}
                <div className="mb-12">
                    <h2 className="text-lg font-semibold mb-4">How it works</h2>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        {[
                            { icon: FileCode, title: 'Write CSS', desc: 'Override any CSS variable or class. Target :root for colors, or specific components.' },
                            { icon: Upload, title: 'Upload .css', desc: 'Drop your .css file here or in Settings > Appearance > Skins. It applies instantly.' },
                            { icon: Paintbrush, title: 'Live preview', desc: 'Changes apply immediately. Remove any time to revert to your base theme.' },
                        ].map(({ icon: Icon, title, desc }) => (
                            <div key={title} className="p-4 rounded-xl border border-border bg-card/50">
                                <Icon size={18} className="text-muted-foreground mb-3" />
                                <p className="text-sm font-medium mb-1">{title}</p>
                                <p className="text-xs text-muted-foreground leading-relaxed">{desc}</p>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Upload section */}
                <div className="mb-12">
                    <h2 className="text-lg font-semibold mb-4">Upload a skin</h2>
                    <div
                        onClick={() => fileInputRef.current?.click()}
                        className="border-2 border-dashed border-border rounded-xl p-8 text-center cursor-pointer hover:border-muted-foreground/40 hover:bg-muted/20 transition-all"
                    >
                        <Upload size={24} className="mx-auto text-muted-foreground mb-3" />
                        <p className="text-sm text-foreground font-medium mb-1">Drop a .css file here or click to browse</p>
                        <p className="text-xs text-muted-foreground">The CSS will be injected as a <code className="font-mono">&lt;style&gt;</code> tag and override default styles.</p>
                        <input
                            ref={fileInputRef}
                            type="file"
                            accept=".css"
                            onChange={handleUpload}
                            className="hidden"
                        />
                    </div>
                </div>

                {/* CSS Variables reference */}
                <div className="mb-12">
                    <h2 className="text-lg font-semibold mb-4">Available CSS variables</h2>
                    <div className="rounded-xl border border-border bg-card/50 overflow-hidden">
                        <pre className="p-4 text-xs font-mono text-muted-foreground overflow-x-auto leading-relaxed">
{`:root {
  --background    /* Main background */
  --foreground    /* Primary text */
  --card          /* Card/panel background */
  --muted         /* Muted/input backgrounds */
  --muted-foreground  /* Secondary text */
  --border        /* Border color */
  --ring          /* Focus ring color */
  --radius        /* Border radius */
  --sidebar-background  /* Sidebar bg */
  --sidebar-foreground  /* Sidebar text */
  --sidebar-border      /* Sidebar border */
  --sidebar-accent      /* Sidebar hover bg */
}`}
                        </pre>
                    </div>
                </div>

                {/* Quickstart */}
                <div className="mb-16">
                    <div className="flex items-center gap-3 mb-6">
                        <h2 className="text-lg font-semibold">Quickstart</h2>
                        <span className="flex items-center gap-1 px-2 py-0.5 text-[10px] font-medium bg-violet-500/10 text-violet-400 border border-violet-500/20 rounded-full">
                            <Sparkles size={10} />
                            AI-powered
                        </span>
                    </div>
                    <p className="text-sm text-muted-foreground mb-6">Answer a few questions and we&apos;ll generate a custom CSS skin for you.</p>

                    {!generatedCSS ? (
                        <div className="space-y-6">
                            {/* Progress */}
                            <div className="flex items-center gap-2 mb-4">
                                {QUESTIONS.map((q, i) => (
                                    <div
                                        key={q.id}
                                        className={`h-1.5 flex-1 rounded-full transition-all duration-300 ${
                                            answers[q.id] ? 'bg-brand' : i === step ? 'bg-muted-foreground/30' : 'bg-muted/50'
                                        }`}
                                    />
                                ))}
                            </div>

                            {/* Current question */}
                            <AnimatePresence mode="wait">
                                <motion.div
                                    key={step}
                                    initial={{ opacity: 0, x: 20 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    exit={{ opacity: 0, x: -20 }}
                                    transition={{ duration: 0.2 }}
                                    className="p-6 rounded-xl border border-border bg-card/50"
                                >
                                    <p className="text-sm font-medium mb-4">{QUESTIONS[step].question}</p>
                                    <div className="flex flex-wrap gap-2">
                                        {QUESTIONS[step].options.map((opt) => (
                                            <button
                                                key={opt.value}
                                                onClick={() => handleAnswer(QUESTIONS[step].id, opt.value)}
                                                className={`px-4 py-2 text-sm rounded-lg border transition-all ${
                                                    answers[QUESTIONS[step].id] === opt.value
                                                        ? 'border-brand bg-brand/10 text-brand'
                                                        : 'border-border text-muted-foreground hover:border-muted-foreground/40 hover:text-foreground'
                                                }`}
                                            >
                                                {answers[QUESTIONS[step].id] === opt.value && <Check size={12} className="inline mr-1.5" />}
                                                {opt.label}
                                                {opt.value.startsWith('#') && (
                                                    <span
                                                        className="inline-block w-3 h-3 rounded-full ml-2 border border-white/10"
                                                        style={{ backgroundColor: opt.value }}
                                                    />
                                                )}
                                            </button>
                                        ))}
                                    </div>
                                </motion.div>
                            </AnimatePresence>

                            {/* Navigation */}
                            <div className="flex items-center justify-between">
                                <button
                                    onClick={() => setStep((s) => Math.max(0, s - 1))}
                                    disabled={step === 0}
                                    className="text-sm text-muted-foreground hover:text-foreground disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
                                >
                                    Back
                                </button>
                                <div className="flex items-center gap-3">
                                    {!isLastQuestion && answers[QUESTIONS[step].id] && (
                                        <button
                                            onClick={() => setStep((s) => s + 1)}
                                            className="flex items-center gap-1 text-sm text-brand hover:text-brand/80 transition-colors"
                                        >
                                            Next <ChevronRight size={14} />
                                        </button>
                                    )}
                                    {allAnswered && (
                                        <button
                                            onClick={handleGenerate}
                                            className="flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg bg-brand text-black hover:bg-brand/90 transition-all"
                                        >
                                            <Sparkles size={14} />
                                            Generate skin
                                        </button>
                                    )}
                                </div>
                            </div>
                        </div>
                    ) : (
                        <motion.div
                            initial={{ opacity: 0, y: 12 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="space-y-4"
                        >
                            <div className="rounded-xl border border-border bg-card/50 overflow-hidden">
                                <div className="flex items-center justify-between px-4 py-2 border-b border-border bg-muted/30">
                                    <span className="text-xs font-mono text-muted-foreground">{answers.vibe || 'custom'}-skin.css</span>
                                    <div className="flex items-center gap-2">
                                        <button
                                            onClick={handleDownload}
                                            className="text-xs text-brand hover:text-brand/80 transition-colors"
                                        >
                                            Download
                                        </button>
                                    </div>
                                </div>
                                <pre className="p-4 text-xs font-mono text-muted-foreground overflow-x-auto max-h-[300px] leading-relaxed">
                                    {generatedCSS}
                                </pre>
                            </div>
                            <div className="flex items-center gap-3">
                                <span className="flex items-center gap-1.5 text-xs text-emerald-400">
                                    <Check size={12} />
                                    Applied to your session
                                </span>
                                <button
                                    onClick={handleReset}
                                    className="text-xs text-muted-foreground hover:text-foreground transition-colors"
                                >
                                    Start over
                                </button>
                            </div>
                        </motion.div>
                    )}
                </div>

                {/* Example skin */}
                <div className="mb-12">
                    <h2 className="text-lg font-semibold mb-4">Example skin</h2>
                    <p className="text-sm text-muted-foreground mb-4">
                        Here&apos;s a minimal example to get you started. Save this as a <code className="font-mono text-foreground/80 bg-muted/50 px-1.5 py-0.5 rounded text-sm">.css</code> file and upload it.
                    </p>
                    <div className="rounded-xl border border-border bg-card/50 overflow-hidden">
                        <div className="px-4 py-2 border-b border-border bg-muted/30">
                            <span className="text-xs font-mono text-muted-foreground">cyberpunk.css</span>
                        </div>
                        <pre className="p-4 text-xs font-mono text-muted-foreground overflow-x-auto leading-relaxed">
{`/* Cyberpunk skin for Tripplet */

:root {
    --background: #0D0D1A !important;
    --card: #141428 !important;
    --foreground: #E0E0FF !important;
    --muted: #1A1A35 !important;
    --muted-foreground: #7070A0 !important;
    --border: #FF006620 !important;
    --ring: #FF0066 !important;
}

/* Neon accent glow on focused inputs */
textarea:focus, input:focus {
    box-shadow: 0 0 12px #FF006640 !important;
}

/* Custom scrollbar */
::-webkit-scrollbar-thumb {
    background: #FF006630 !important;
}
`}
                        </pre>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}
