'use client';

import { LandingHeader } from '@/components/ui/landing-header';
import { LandingFooter } from '@/components/ui/landing-footer';
import { motion } from 'framer-motion';

const ease = [0.25, 0.46, 0.45, 0.94] as const;

const fadeUp = {
    hidden: { opacity: 0, y: 20, filter: 'blur(8px)' },
    visible: { opacity: 1, y: 0, filter: 'blur(0px)', transition: { duration: 0.6, ease } },
};

const sections = [
    {
        title: '1. Acceptance of Terms',
        content: `By accessing or using the Tripplet platform ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service. We reserve the right to update these terms at any time, and your continued use of the Service constitutes acceptance of those changes.`,
    },
    {
        title: '2. Description of Service',
        content: `Tripplet provides an AI-powered platform that includes conversational chat, code generation, and web search capabilities. The Service is powered by multiple AI models including Taipei 4, Majuli 4, and Suzhou 4. Features and capabilities may change, expand, or be discontinued at our discretion.`,
    },
    {
        title: '3. User Accounts',
        content: `To access certain features of the Service, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate, current, and complete information during registration and keep your account information up to date. Guest users may access limited features without an account, subject to usage limits.`,
    },
    {
        title: '4. Acceptable Use',
        content: `You agree not to use the Service to: (a) generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable; (b) impersonate any person or entity; (c) attempt to gain unauthorized access to the Service or its systems; (d) interfere with or disrupt the Service; (e) use the Service for any purpose that violates applicable local, state, national, or international law; (f) generate content that infringes on the intellectual property rights of others; or (g) use automated means to access the Service beyond what is provided through our API.`,
    },
    {
        title: '5. Content and Intellectual Property',
        content: `You retain ownership of the content you input into the Service ("Input Content"). You are granted a non-exclusive license to use any content generated by the Service ("Output Content") for personal or commercial purposes. We do not claim ownership of Output Content. However, similar or identical Output Content may be generated for other users. You are responsible for ensuring your use of Output Content complies with applicable laws and does not infringe on third-party rights.`,
    },
    {
        title: '6. AI-Generated Content Disclaimer',
        content: `The Service uses artificial intelligence to generate responses and code. AI-generated content may contain errors, inaccuracies, or biases. You acknowledge that: (a) AI outputs should be reviewed before use in critical applications; (b) Tripplet does not guarantee the accuracy, completeness, or reliability of any AI-generated content; (c) you are solely responsible for how you use AI-generated content; and (d) AI-generated content should not be treated as professional advice (legal, medical, financial, or otherwise).`,
    },
    {
        title: '7. Privacy and Data',
        content: `Your privacy is important to us. Our collection and use of personal information is described in our Privacy Policy. By using the Service, you consent to the collection and use of your information as described therein. We may use anonymized and aggregated data from the Service to improve our AI models and platform. Conversations and generated content may be stored to provide service continuity, but are not shared with third parties except as described in our Privacy Policy.`,
    },
    {
        title: '8. Subscriptions and Payments',
        content: `Certain features of the Service may require a paid subscription. Subscription fees are billed in advance on a recurring basis (monthly or yearly). You may cancel your subscription at any time, and cancellation will take effect at the end of the current billing period. We reserve the right to change subscription prices with 30 days' notice. Refunds are handled on a case-by-case basis.`,
    },
    {
        title: '9. Service Availability',
        content: `We strive to maintain the Service at all times but do not guarantee uninterrupted availability. The Service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control. We are not liable for any loss or damage resulting from Service unavailability. We reserve the right to modify, suspend, or discontinue any part of the Service at any time.`,
    },
    {
        title: '10. Limitation of Liability',
        content: `To the maximum extent permitted by law, Tripplet shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from: (a) your use of or inability to use the Service; (b) any content generated by the Service; (c) unauthorized access to or alteration of your data; or (d) any third-party conduct on the Service.`,
    },
    {
        title: '11. Open Source License',
        content: `Tripplet is released into the public domain under the Unlicense. Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means. This license applies to the software itself and does not extend to third-party services, APIs, or models used by the platform.`,
    },
    {
        title: '12. Contact',
        content: `If you have questions about these Terms of Service, you can reach us through our platform. These terms were last updated in March 2026.`,
    },
];

export default function Terms() {
    return (
        <div className="flex min-h-screen w-full flex-col bg-background grain-overlay relative">
            <LandingHeader />

            <main className="grow">
                <section className="mx-auto w-full max-w-3xl px-4 pt-32 pb-20 md:pt-40 md:pb-28">
                    <motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: 0.05 } } }}>
                        <motion.p variants={fadeUp} className="text-sm font-medium text-muted-foreground mb-3">
                            Legal
                        </motion.p>
                        <motion.h1 variants={fadeUp} className="gradient-text text-3xl font-bold tracking-tight md:text-4xl">
                            Terms of Service
                        </motion.h1>
                        <motion.p variants={fadeUp} className="mt-3 text-muted-foreground">
                            Last updated: March 2026
                        </motion.p>

                        <div className="mt-12 space-y-8">
                            {sections.map((section, i) => (
                                <motion.div
                                    key={section.title}
                                    initial={{ opacity: 0, y: 16, filter: 'blur(4px)' }}
                                    whileInView={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
                                    viewport={{ once: true, margin: '-40px' }}
                                    transition={{ duration: 0.4, delay: 0.02 }}
                                >
                                    <h2 className="text-base font-semibold mb-2">{section.title}</h2>
                                    <p className="text-sm text-muted-foreground leading-relaxed">{section.content}</p>
                                </motion.div>
                            ))}
                        </div>
                    </motion.div>
                </section>
            </main>

            <LandingFooter />
        </div>
    );
}
